---
title: "20220613 FINDEM table 1"
author: "A. Meulenbeld"
date: "13-6-2022"
output: html_document
---

```{r setup, include=FALSE}
library("table1")
library("flextable")
library(haven)
library(dplyr)

data_teller <- read_sav("baseline_teller.sav")
load("findem_clean.Rdta")

```

```{r process datasets}
data_clean <- subset(data_clean, !is.na(data_clean$Cluster))
data_clean <- subset(data_clean, data_clean$Meetweek==0)
data_clean <- merge(data_clean, data_teller,  by = "KeyID")
data_clean$stap2 <- as.factor(data_clean$stap)
data_clean$stap2 <- recode_factor(data_clean$stap2, "2.1"="2","2.2"="2", "3.1"="3", "3.2"="3")

data_clean$Ndonation <- data_clean$TotaalOpBaseline
data_clean$Ndonation[data_clean$Ndonation>0] <- 1
data_clean$Ndonation <- recode_factor(data_clean$Ndonation, `1`="0",`0`="1")
```

```{r}
#for pre menopausal females
prefemales <- subset(data_clean, data_clean$Gender=="Female" & data_clean$PostMeno==0)
prefemalest1<-table1(~ Age + Hb + Ferritin + Height + Weight +TotaalOpBaseline + Previous2yr + factor(IronDef) + factor(HbDef) + factor(Return) + factor(ReturnOpTijd) + factor(Ndonation) | factor(stap2), data = prefemales, caption = "Females", render.continuous=c(.="Mean (SD)", .="Median [Q1, Q3]"), render.categorical=c(.="FREQ (PCT)"))

#for post menopausal females
postfemales <- subset(data_clean, data_clean$Gender=="Female" & data_clean$PostMeno==1)
postfemalest1<-table1(~ Age + Hb + Ferritin + Height + Weight +TotaalOpBaseline + Previous2yr + factor(IronDef) + factor(HbDef) + factor(Return) + factor(ReturnOpTijd) + factor(Ndonation) | factor(stap2), data = postfemales, caption = "Females", render.continuous=c(.="Mean (SD)", .="Median [Q1, Q3]"), render.categorical=c(.="FREQ (PCT)"))

#for males
males <- subset(data_clean, data_clean$Gender=="Male")
malest1<- table1(~ Age + Hb + Ferritin + Height + Weight +TotaalOpBaseline + Previous2yr + factor(IronDef) + factor(HbDef) + factor(Return) + factor(ReturnOpTijd) + factor(Ndonation) | factor(stap2), data = males, caption = "Males", render.continuous=c(.="Mean (SD)", .="Median [Q1, Q3]"), render.categorical=c(.="FREQ (PCT)"))

```

```{r}
currentDate <- format(Sys.time(), "%Y-%m-%d")
FolderName <- paste("HTML tables/", currentDate,sep="")
dir.create(FolderName)

FileName <- paste("HTML tables/", currentDate, "/prefemales_t1.html",sep="")
t1flex(prefemalest1) %>% 
  save_as_html(path=FileName)

FileName <- paste("HTML tables/", currentDate, "/postfemales_t1.html",sep="")
t1flex(postfemalest1) %>% 
  save_as_html(path=FileName)

FileName <- paste("HTML tables/", currentDate, "/males_t1.html",sep="")
t1flex(malest1) %>% 
  save_as_html(path=FileName)

```
